language: rust
sudo: false

# Cache `cargo install`ed tools, but don't cache the project's `target`
# directory (which ends up over-caching and filling all disk space!)
cache:
  directories:
    - /home/travis/.cargo

DEPLOY_TO_GITHUB: &DEPLOY_TO_GITHUB
  before_deploy:
    - git config --local user.name "Ashley Williams"
    - git config --local user.email "ashley666ashley@gmail.com"
    - name="wasm-pack-$TRAVIS_TAG-$TARGET"
    - mkdir $name
    - cp target/$TARGET/release/wasm-pack $name/
    - cp README.md LICENSE-MIT LICENSE-APACHE $name/
    - tar czvf $name.tar.gz $name
  deploy:
    provider: releases
    api_key: GH_TOKEN
    file: wasm-pack-$TRAVIS_TAG-$TARGET.tar.gz
    skip_cleanup: true
    on:
      branch: master
      tags: true

matrix:
  include:

  - name: Tests
    env: RUST_BACKTRACE=1
    rust: stable
    script:
    - cargo test --all --locked
    - rustup component add rustfmt-preview
    - cargo fmt --version
    - cargo fmt --all -- --check
    - rustup component add clippy-preview
    - cargo clippy --version
    - cargo clippy

  - name: Linux Binary
    env: TARGET=x86_64-unknown-linux-musl
    rust: stable
    before_script: rustup target add $TARGET
    script: cargo build --release --target $TARGET --locked
    addons:
      apt:
        packages:
          - musl-tools
    <<: *DEPLOY_TO_GITHUB

  - name: macOS Binary
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    rust: stable
    script: cargo build --release --target $TARGET --locked
    install: true
    <<: *DEPLOY_TO_GITHUB

notifications:
  email:
    on_success: never
