jobs:
  - job: test
    displayName: "Run tests, cargo fmt, and cargo clippy"
    steps:
      - template: ci/azure-install-rust.yml
      - script: cargo test --locked
      - script: cargo fmt --all -- --check
      - script: cargo clippy
